// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SearchTagsController from "./search_tags_controller"
application.register("search-tags", SearchTagsController)

import SearchWordsController from "./search_words_controller"
application.register("search-words", SearchWordsController)

import TagController from "./tag_controller"
application.register("tag", TagController)
